### ISSUE TITLE
Preview/Download Functions Still Not Working

### ISSUE THREAD

**Issue by cjsmith9** [harish-io/Impressionist#10]
I am still not able to preview or download my presentation.  I continue to get these error messages using Google Chrome on Mac OSX:

XMLHttpRequest cannot load file://localhost/Users/chris/Desktop/hsivaramx-Impressionist-4af0fad/alpha3/server/generatePreview.php. Origin null is not allowed by Access-Control-Allow-Origin.

XMLHttpRequest cannot load file://localhost/Users/chris/Desktop/hsivaramx-Impressionist-4af0fad/alpha3/server/generateArchive.php. Origin null is not allowed by Access-Control-Allow-Origin.

Sorry to post this again, but I tried all of the suggested fixes and continue to get this issue.

**Comment by harish-io** [comment]
Have you hosted the PHP files under a webserver? The error that you are getting suggests you may not be. Could you please check?

**Comment by cjsmith9** [comment]
I am having some serious issues with getting my webserver to work.  I will try to fix that before coming back to this.  Thank you for your help.

**Comment by cjsmith9** [comment]
I have successfully setup my webserver and everything seems to be working great!  Thanks so much for all your help and good luck moving forward!

**Comment by harish-io** [comment]
Thanks, glad to know its working. Keep logging issues as you find them!
