### ISSUE TITLE
text issues

### ISSUE THREAD

**Issue by tony1223** [harish-io/Impressionist#18]
It's not addable and editable after I create some texts. 

Not sure what's happening , it's still happening after I "open" the slide file,
I can't add new text in the slide after the issue happened.

Here's the demo for how it broken.
http://screencast.com/t/qQyX5XGiZY

**Comment by tony1223** [comment]
If I delete the "This is sample text" dom node manually from browser inspector , it start to work.

**Comment by tony1223** [comment]
Here's a dom view for the wrong node.
http://screencast.com/t/kkC0EBcK

**Comment by tony1223** [comment]
And after the case , this document will get errors and can't be previewed and downloaded. 

It could be reproduce even after  I open the slider again.

(I will try to get more error message and the source object out from local storage if possible to help us reproduce this.)

**Comment by tony1223** [comment]
https://gist.github.com/b30f179db63df3fd770b 
Here's the string I  get from the getItem("myslider") .

And if in the case , I couldn't preview and download the presentation due to javascript error, 
I think it's ok to have a simple error handling code to handle this.

**Comment by harish-io** [comment]
This should be fixed, after couple of recent check-ins. Please check. Thanks!
