### ISSUE TITLE
Failed To Change Text

### ISSUE THREAD

**Issue by goldalworming** [harish-io/Impressionist#2]
I cannot change 'this is sample text'

it's always back to default..

I use google chrome

**Comment by harish-io** [comment]
Unable to reproduce what you are seeing. Can you please elaborate the steps to reproduce this issue? Thanks!

**Comment by goldalworming** [comment]
create presentation
click text button
click the presentation area then it show this is sample text
double click then it show input text, 
I change the text but then I cannot enter or save my text...I click outside input area..the text just return to default

**Comment by forty4** [comment]
I have the same problem. 
I cannot change the text when I hosted the Impressionist on my computer. (localhost, Apache, MacOS X, Chrome)

**Comment by goldalworming** [comment]
I've tried in safari and still not working...

**Comment by danns** [comment]
I'm having the same issue. I also use the latest version of chrome on windows 7 and it won't let me change the text to what I want.

**Comment by cjsmith9** [comment]
I have had the same problem, in both Chrome and Safari.

**Comment by harish-io** [comment]
Hey folks, have you tried syncing to the alpha 2 branch? I am working on merging the changes to the main branch - but in the meanwhile, please check the alpha 2 branch. Thanks!

**Comment by cjsmith9** [comment]
Alpha 2 branch is working great so far!  Thanks for the tip!

**Comment by harish-io** [comment]
Thanks for the validation @cjsmith9 ! Closing this issue.
