### ISSUE TITLE
drag and drop issue

### ISSUE THREAD

**Issue by tony1223** [harish-io/Impressionist#22]
When we drag and drop , 
the item is required for top have to be less than 400 and left have to be less than 600 , 

That doesn't make any sense for my 1920*1080 screen , is there's any concern for this ?

I would suggest to remove this restriction.

**Comment by harish-io** [comment]
Partial fix for this issue done. There is no restriction on dragging objects around now. However, the context menu has a positioning bug if you move out of the working region. 

This one would be an edge case, I will not be prioritizing that cosmetic issue, for the time being.

**Comment by harish-io** [comment]
Fixed the cosmetic errors as well. Contextbar is now back at the main tool bar.
