### ISSUE TITLE
Strut & Impressionist - Join projects?

### ISSUE THREAD

**Issue by tantaman** [harish-io/Impressionist#28]
Hey.  I just recently found Impressionist.  I've been working on a similar project for authoring ImpressJS presentations called Strut.  It's also based on Twitter bootstrap but makes use of RequireJS and BackboneJS in order to keep the code modular and object oriented.  

Maybe we can collaborate?  I think both projects are about on par as far as features go.

Here is Strut if you want to see what I've got so far:
http://www.youtube.com/watch?v=zA5s8wwme44&feature=share
https://github.com/tantaman/Strut

live demo on github:
http://tantaman.github.com/Strut/client/web/index.html

**Comment by harish-io** [comment]
Hey there - Good work at Strut. I am glad to see the approach that you have taken is similar to what I have which validates there is merit in the way we both are building it. 

I see that you have done your development using coffeescript while I have kept it plain javascript. I am unsure as to how productive it would be to spend time merging code between projects. I will add strut to my Readme and I think its a good thing for the user to have more than one option to do presentations visually for impress.js

Once again, good work!
