### ISSUE TITLE
Bugs preventing open from working

### ISSUE THREAD

**Issue by masukomi** [harish-io/Impressionist#40]
Using chrome on OS X.

After saving, choose "Open" from the file menu.

Listed saves don't stay selected so clicking "ok" doesn't have anything to act on.

Double clicking (as per instructions) also fails to open anything.

I assume these probably have the same underlying issue.

**Comment by harish-io** [comment]
The alpha3 branch is not under active development. Request you to look at the recent changes and see if that works for you. Thanks!

**Comment by masukomi** [comment]
Sorry for not being more clear. This bug report _is_ against the recent changes (the 0.2 one with the cat up in the corner).

[update] Er nevermid. Scratch that. I got confused between this bug report and a different one I'd filed.
