### ISSUE TITLE
Few issues!

### ISSUE THREAD

**Issue by vaidaslamanauskas** [harish-io/Impressionist#44]
Hey Harish and guys who contributing to the code,
Few major issues:
1. Text align doesn't work.
2. Headings doesn't work.
3. Added images show up really small. (also need ability to resize them)
4. Old presentations merges with new one's in preview.
5. Close buttons doesn't work. #43 
6. After adding new header, Style needs to be set again.
7. And you can somehow edit the text in preview :)

That's it for now.

**Comment by harish-io** [comment]
1 - feature is absent. It needs to be implemented.
2. Headings do work (this seems work fine for me, could you help me with your testing setup?) http://harish.io/impressionist
3. There is no code  that changes dimensions of added images (this seems work fine for me, could you help me with your testing setup?) Resize images: TODO
4. Could you send a screenshot please?
5. TODO
6. TODO
7. My bad . TODO

**Comment by vaidaslamanauskas** [comment]
1. Okay
2. Sorry I meant to say that headings like H1, H2, H3 doesn't work. Can't change the size.
3. I tested on Windows 7 Ultimate 32-bits from Google Chrome v.27.0.1453.116 (newest).

And about 4; 3.
![capture](https://f.cloud.github.com/assets/4195325/692003/2cd5031a-dbe9-11e2-900b-1931b4ebee53.png)

**Comment by jerrymannel** [comment]
I'm also seeing the same problems as reported by Vaidis on (2)
The headings don't seem to be working.

I'm on Ubuntu 12.04 64bit, Chrome Version 28.0.1500.52
