### ISSUE TITLE
Preview/Download Functions Not Working

### ISSUE THREAD

**Issue by cjsmith9** [harish-io/Impressionist#8]
I can't seem to get the preview or download functions to work at all.  I saw in the video on Youtube that Previewing should just open a new tab with the presentation in it, but it doesn't work for me.  When i try right clicking on preview and opening in a new tab, it just opens a new project.

EDIT: I am running in Google Chrome on Mac OS X and I'm using the Alpha 2 branch files.

**Comment by goldalworming** [comment]
I got same problem but then I change the permissions in my linux and it's work

it's work in ubuntu and windows to export the code...but the output code cannot work...

**Comment by goldalworming** [comment]
I copied jquery.js, folder scripts, pics and css inside folder output and it works great...
even in firefox, it works

awesome...thanks for great tool 
presentation won't same anymore

**Comment by harish-io** [comment]
Please check if you have a pop-up blocker enabled in your browser. if you do, temporarily disable it and you will see the preview and download working fine. Thanks!

**Comment by cjsmith9** [comment]
I am still getting this error message in the console for Google Chrome:

XMLHttpRequest cannot load file://localhost/Users/chris/Desktop/hsivaramx-Impressionist-4af0fad/alpha3/server/generatePreview.php. Origin null is not allowed by Access-Control-Allow-Origin.

I have tried copying the suggested files/folders into the output folder and checked my pop-ups setting in chrome.
